### ISSUE TITLE
Toggling two or more classes

### ISSUE THREAD

**Issue by slowas** [jasepellerin/vue-scroll-class#1]
Hello, I'am have issue toggling more than one class how am can do it. P.S sorry for bad english

**Comment by jasepellerin** [comment]
To add multiple classes, you should be able to simple add multiple `v-scroll-class` tags to your element. For example:

```html
<nav class="nav-bar" v-scroll-class="300" v-scroll-class:otherClass="500">
```

Let me know if that doesn't work for you!

**Comment by jasepellerin** [comment]
Closing for now. Feel free to reopen if it needs to be looked at.
